name: CI

on:
  # Run on pushes to master
  push:
    branches:
      - main
  # Run on pull requests (automatically uses PR in docker name)
  pull_request:
  # Also run on a schedule (once a month)
  schedule:
    - cron: '0 0 1 */1 *'

jobs:
  test-examples:
    name: Test of target ${{ matrix.target }}
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/sancus-tee/sancus-main/sancus-devel-64:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        target: [secure_memcmp, unwrap-break, auth-ex-break, compiler-equal ]

    steps:
      - uses: actions/checkout@v2
        name: Pull repository
      - run: cd ${{ matrix.target }} ; make clean sim | tee sim.out ; ! grep -iqE "fail|error:" sim.out
        name: Build and run ${{ matrix.target }}
